using System;
using Users.Common.Models;
using Users.Common.Services;

namespace Users.Cmd
{
    class Program
    {
        static void Main(string[] args)
        {
            string userInputEmail;
            string userInputPassword;
            var userService = new UserService();
            bool isRunning = true;
            while (isRunning)
            {
                Console.WriteLine("Choose your option\n[1] Login\n[2] Register\n[3] Exit");
                int? userOption = null;
                try
                {
                    userOption = Convert.ToInt32(Console.ReadLine());
                }
                catch (FormatException) { }

                switch (userOption)
                {
                    case 1:
                        Console.WriteLine("\nEnter your email and password:");
                        Console.Write("Email: ");
                        userInputEmail = Console.ReadLine();
                        Console.Write("Password: ");
                        userInputPassword = Console.ReadLine();

                        if (userService.Get(userInputEmail) == null)
                        {
                            Console.WriteLine("You are not a registered user, please register.\n");
                        }
                        else
                        {
                            var loginRespons = userService.Login(userInputEmail, userInputPassword);
                            if (!loginRespons.Success)
                            {
                                Console.WriteLine("Password is not correct!");
                            }
                            else
                            {
                                Console.WriteLine("You are logged in!");
                            }
                        }
                        break;

                    case 2:
                        CreateNewUser(userService);
                        break;

                    case 3:
                        Console.WriteLine("Bye!");
                        isRunning = false;
                        break;

                    default:
                        Console.WriteLine("You have to choose one of the options in te menu!");
                        break;
                }
            }
        }
        private static void CreateNewUser(UserService userService)
        {
            var newUser = new User();
            Console.Write("Email: ");
            newUser.Email = Console.ReadLine();
            if (userService.Get(newUser.Email) == null)
            {
                Console.Write("Name: ");
                newUser.Name = Console.ReadLine();
                Console.Write("Phone: ");
                newUser.Phone = Console.ReadLine();
                Console.Write("Would you like to recieve our newsletter? Y/N: ");
                newUser.SubscribeToNewsletter = Console.ReadLine() == "Y" ? true : false;
                var passwordService = new PasswordService();
                var newPassword = passwordService.GeneratePassword(8);
                newUser.Password = newPassword;
                Console.Write($"{newUser.Name}, you are now registered and your autogenerated password is: {newPassword}\n");
                userService.UsersStored.Add(newUser);
            }
            else
            {
                Console.WriteLine("The email adress already exists, try to login with your password.");
            }
                
        }
    }
}
